version: "3.9"

services:
    main-api:
        build: ShopAPI/
        restart: always
        ports:
            - 3000:80
        depends_on:
            - sql-server
    
    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=PassW0rd
            - MSSQL_TCP_PORT = 1433